# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e95be433ca42bde4b1b6576bd20299e7106ce0de752e39720baba3a86774d4a3756229c6927a073f57b076695ba1dcf30e12b87c7f01563f8441062c8763274

test:
  secret_key_base: c760988a62837ad52298fbc7e54a58e67b8f68aa8ba50b9f67d0f6ea80e114377e77726a1f2619ec87313b44623462cafaf114feb73f000b9aa35abf36068051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
